[tool.poetry]
name = "scenic-reasoning"
version = "0.1.0"
description = "Can VLMs reason about the physical relationships of everyday scenes? We find out in the realm of robotics and autonomous driving"
authors = ["Karim Elmaaroufi <elmaaroufi@berkeley.edu>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "scenic_reasoning"}]

[tool.poetry.dependencies]
python = "^3.9"
mlx = "^0.19.0"
torch = "^2.5.0"
timm = "^1.0.11"
ipykernel = "^6.29.5"
transformers = "^4.45.2"
ultralytics = "^8.3.21"


[tool.poetry.scripts]
install_depth_pro = "scenic_reasoning.src.scenic_reasoning.setup:install_depth_pro"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
