name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Run check.ch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Execute Permissions
        run: chmod +x check.ch

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install

      - name: Run check.ch
        run: ./check.ch
